# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ChangeRecipe.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeRecipe(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        ChangeRecipe = QWidget()

        self.setObjectName("ChangeRecipe")
        self.resize(300, 400)
        self.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(ChangeRecipe)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(0, 0, 80, 30))
        self.btn_cancel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_cancel.clicked.connect(lambda: self.controller.showRecipe())#showRecipe

        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(220, 0, 80, 30))
        self.btn_save.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.btn_save.setObjectName("btn_save")
        self.btn_save.clicked.connect(lambda: self.controller.showRecipe())#showRecipe

        self.text_type_of_recipe = QtWidgets.QLabel(self.centralwidget)
        self.text_type_of_recipe.setGeometry(QtCore.QRect(0, 90, 300, 61))
        self.text_type_of_recipe.setStyleSheet("background-color: rgb(166, 166, 166);\n"
"background-color: rgb(255, 255, 255);")
        self.text_type_of_recipe.setObjectName("text_type_of_recipe")
        self.text_time = QtWidgets.QLabel(self.centralwidget)
        self.text_time.setGeometry(QtCore.QRect(240, 260, 60, 30))
        self.text_time.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_time.setObjectName("text_time")
        self.text_name_of_recipe = QtWidgets.QLabel(self.centralwidget)
        self.text_name_of_recipe.setGeometry(QtCore.QRect(0, 30, 300, 30))
        self.text_name_of_recipe.setStyleSheet("color: rgb(177, 177, 177);\n"
"")
        self.text_name_of_recipe.setObjectName("text_name_of_recipe")
        self.text_ingridients = QtWidgets.QLabel(self.centralwidget)
        self.text_ingridients.setGeometry(QtCore.QRect(0, 150, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_ingridients.setFont(font)
        self.text_ingridients.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_ingridients.setObjectName("text_ingridients")
        self.text_all_ingridients = QtWidgets.QLabel(self.centralwidget)
        self.text_all_ingridients.setGeometry(QtCore.QRect(0, 180, 300, 80))
        self.text_all_ingridients.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_all_ingridients.setObjectName("text_all_ingridients")
        self.text_quantity_ingr = QtWidgets.QLabel(self.centralwidget)
        self.text_quantity_ingr.setGeometry(QtCore.QRect(250, 180, 50, 80))
        self.text_quantity_ingr.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 255);")
        self.text_quantity_ingr.setObjectName("text_quantity_ingr")
        self.text_cook = QtWidgets.QLabel(self.centralwidget)
        self.text_cook.setGeometry(QtCore.QRect(0, 290, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_cook.setFont(font)
        self.text_cook.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_cook.setObjectName("text_cook")
        self.text_full_description = QtWidgets.QLabel(self.centralwidget)
        self.text_full_description.setGeometry(QtCore.QRect(0, 320, 300, 80))
        self.text_full_description.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-color: rgb(178, 171, 255);")
        self.text_full_description.setObjectName("text_full_description")
        self.text_change_recipe = QtWidgets.QLabel(self.centralwidget)
        self.text_change_recipe.setGeometry(QtCore.QRect(80, 0, 140, 30))
        self.text_change_recipe.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_change_recipe.setObjectName("text_change_recipe")
        self.text_types = QtWidgets.QLabel(self.centralwidget)
        self.text_types.setGeometry(QtCore.QRect(0, 60, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_types.setFont(font)
        self.text_types.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_types.setObjectName("text_types")
        self.text_time_of_cook = QtWidgets.QLabel(self.centralwidget)
        self.text_time_of_cook.setGeometry(QtCore.QRect(0, 260, 240, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_time_of_cook.setFont(font)
        self.text_time_of_cook.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_time_of_cook.setObjectName("text_time_of_cook")
        self.btn_cancel.raise_()
        self.btn_save.raise_()
        self.text_type_of_recipe.raise_()
        self.text_name_of_recipe.raise_()
        self.text_ingridients.raise_()
        self.text_all_ingridients.raise_()
        self.text_quantity_ingr.raise_()
        self.text_cook.raise_()
        self.text_full_description.raise_()
        self.text_change_recipe.raise_()
        self.text_types.raise_()
        self.text_time.raise_()
        self.text_time_of_cook.raise_()

        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ChangeRecipe)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(ChangeRecipe)
        QtCore.QMetaObject.connectSlotsByName(ChangeRecipe)

    def retranslateUi(self, ChangeRecipe):
        _translate = QtCore.QCoreApplication.translate
        ChangeRecipe.setWindowTitle(_translate("ChangeRecipe", "Поваренная книга"))
        self.btn_cancel.setText(_translate("ChangeRecipe", "Х Отмена"))
        self.btn_save.setText(_translate("ChangeRecipe", "Сохранить"))
        self.text_type_of_recipe.setText(_translate("ChangeRecipe", "десерт \n"
"пирог \n"
"америкаская кухня"))
        self.text_time.setText(_translate("ChangeRecipe", "  40 мин."))
        self.text_name_of_recipe.setText(_translate("ChangeRecipe", "Название"))
        self.text_ingridients.setText(_translate("ChangeRecipe", "Ингридиенты:"))
        self.text_all_ingridients.setText(_translate("ChangeRecipe", "Темный шоколад \n"
"Сливочное масло \n"
"Куриное яйцо \n"
"Сахар \n"
"Пшеничная мука"))
        self.text_quantity_ingr.setText(_translate("ChangeRecipe", "100гр \n"
"180гр \n"
"4шт \n"
"200гр \n"
"100гр"))
        self.text_cook.setText(_translate("ChangeRecipe", "Приготовление:"))
        self.text_full_description.setText(_translate("ChangeRecipe", "Масло и шоколад нужно растопить, для этого \n"
"шоколад ломаем кусочками и кладём \n"
"его вместе с маслом в ёмкость, в которой \n"
"будем их растапливать. Растапливаем шоколад \n"
" с маслом на водяной бане или в \n"
" микроволновой печи. "))
        self.text_change_recipe.setText(_translate("ChangeRecipe", "   Изменение рецепта"))
        self.text_types.setText(_translate("ChangeRecipe", "Разделы:"))
        self.text_time_of_cook.setText(_translate("ChangeRecipe", "Время приготовления"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangeRecipe = QtWidgets.QMainWindow()
    ui = Ui_ChangeRecipe()
    ui.setupUi(ChangeRecipe)
    ChangeRecipe.show()
    sys.exit(app.exec_())
