# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Entry_in_account.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Entry_account(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        Entry_account = QWidget()

        self.setObjectName("Entry_account")
        self.resize(300, 400)
        self.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(Entry_account)
        self.centralwidget.setObjectName("centralwidget")
        self.text_entry_acc = QtWidgets.QLabel(self.centralwidget)
        self.text_entry_acc.setGeometry(QtCore.QRect(0, 60, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.text_entry_acc.setFont(font)
        self.text_entry_acc.setStyleSheet("color: rgb(156, 156, 255);")
        self.text_entry_acc.setObjectName("text_entry_acc")

        self.text_name = QtWidgets.QLabel(self.centralwidget)
        self.text_name.setGeometry(QtCore.QRect(0, 110, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.text_name.setFont(font)
        self.text_name.setMouseTracking(False)
        self.text_name.setAcceptDrops(False)
        self.text_name.setStyleSheet("color: rgb(77, 77, 77);")
        self.text_name.setScaledContents(False)
        self.text_name.setWordWrap(True)
        self.text_name.setOpenExternalLinks(False)
        self.text_name.setObjectName("text_name")

        self.btn_dalee = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dalee.setGeometry(QtCore.QRect(90, 330, 120, 30))
        self.btn_dalee.setStyleSheet("background-color: rgb(178, 171, 255);\n"
"color: rgb(255, 255, 255);")
        self.btn_dalee.setObjectName("btn_dalee")
        self.btn_dalee.clicked.connect(lambda: self.controller.showProfile())#showProfile


        self.text_password = QtWidgets.QLabel(self.centralwidget)
        self.text_password.setGeometry(QtCore.QRect(0, 190, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.text_password.setFont(font)
        self.text_password.setMouseTracking(False)
        self.text_password.setAcceptDrops(False)
        self.text_password.setStyleSheet("color: rgb(77, 77, 77);")
        self.text_password.setScaledContents(False)
        self.text_password.setWordWrap(True)
        self.text_password.setOpenExternalLinks(False)
        self.text_password.setObjectName("text_password")

        self.text_name_in = QtWidgets.QLabel(self.centralwidget)
        self.text_name_in.setGeometry(QtCore.QRect(40, 160, 200, 30))
        self.text_name_in.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"color: rgb(206, 206, 206);")
        self.text_name_in.setObjectName("text_name_in")

        self.text_passowrd_in = QtWidgets.QLabel(self.centralwidget)
        self.text_passowrd_in.setGeometry(QtCore.QRect(40, 240, 200, 30))
        self.text_passowrd_in.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"color: rgb(206, 206, 206);")
        self.text_passowrd_in.setObjectName("text_passowrd_in")

        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Entry_account)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(Entry_account)
        QtCore.QMetaObject.connectSlotsByName(Entry_account)

    def retranslateUi(self, Entry_account):
        _translate = QtCore.QCoreApplication.translate
        Entry_account.setWindowTitle(_translate("Entry_account", "Поваренная книга"))
        self.text_entry_acc.setText(_translate("Entry_account", "Вход в аккаунт"))
        self.text_name.setText(_translate("Entry_account", "Имя пользователя:"))
        self.btn_dalee.setText(_translate("Entry_account", "Далее"))
        self.text_password.setText(_translate("Entry_account", "Пароль:"))
        self.text_name_in.setText(_translate("Entry_account", "имя"))
        self.text_passowrd_in.setText(_translate("Entry_account", "пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Entry_account = QtWidgets.QMainWindow()
    ui = Ui_Entry_account()
    ui.setupUi(Entry_account)
    Entry_account.show()
    sys.exit(app.exec_())
