# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_first.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_First(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        First = QWidget()

        self.setObjectName("First")
        self.resize(300, 400)
        self.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(First)

        self.centralwidget.setObjectName("centralwidget")
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        self.label_welcome.setGeometry(QtCore.QRect(0, 60, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_welcome.setFont(font)
        self.label_welcome.setStyleSheet("color: rgb(156, 156, 255);")
        self.label_welcome.setObjectName("label_welcome")

        self.label_vypolnite_vhod = QtWidgets.QLabel(self.centralwidget)
        self.label_vypolnite_vhod.setGeometry(QtCore.QRect(0, 140, 300, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_vypolnite_vhod.setFont(font)
        self.label_vypolnite_vhod.setMouseTracking(False)
        self.label_vypolnite_vhod.setAcceptDrops(False)
        self.label_vypolnite_vhod.setStyleSheet("color: rgb(156, 156, 255);")
        self.label_vypolnite_vhod.setScaledContents(False)
        self.label_vypolnite_vhod.setWordWrap(True)
        self.label_vypolnite_vhod.setOpenExternalLinks(False)
        self.label_vypolnite_vhod.setObjectName("label_vypolnite_vhod")

        self.btn_entry = QtWidgets.QPushButton(self.centralwidget)
        self.btn_entry.setGeometry(QtCore.QRect(90, 250, 120, 30))
        self.btn_entry.setStyleSheet("background-color: rgb(178, 171, 255);\n"
"color: rgb(255, 255, 255);")
        self.btn_entry.setObjectName("btn_entry")
        self.btn_entry.clicked.connect(lambda: self.controller.showCreate())#showCreate


        self.btn_registration = QtWidgets.QPushButton(self.centralwidget)
        self.btn_registration.setGeometry(QtCore.QRect(90, 290, 120, 30))
        self.btn_registration.setStyleSheet("background-color: rgb(178, 171, 255);\n"
"color: rgb(255, 255, 255);")
        self.btn_registration.setObjectName("btn_registration")

        self.btn_later = QtWidgets.QPushButton(self.centralwidget)
        self.btn_later.setGeometry(QtCore.QRect(90, 330, 120, 30))
        self.btn_later.setStyleSheet("color: rgb(178, 171, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.btn_later.setObjectName("btn_later")
        self.btn_later.clicked.connect(lambda: self.controller.showProfile())#ShowProfile

        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(First)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(First)
        QtCore.QMetaObject.connectSlotsByName(First)

    def retranslateUi(self, First):
        _translate = QtCore.QCoreApplication.translate
        First.setWindowTitle(_translate("First", "Поваренная книга"))
        self.label_welcome.setText(_translate("First", "Добро Пожаловать!"))
        self.label_vypolnite_vhod.setText(_translate("First", "Выполните вход в профиль или зарегистрируйтесь."))
        self.btn_entry.setText(_translate("First", "Вход"))
        self.btn_registration.setText(_translate("First", "Регистрация"))
        self.btn_later.setText(_translate("First", "Позже"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    First = QtWidgets.QMainWindow()
    ui = Ui_First()
    ui.setupUi(First)
    First.show()
    sys.exit(app.exec_())
