# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Recipe.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recipe(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        Recipe = QWidget()

        self.setObjectName("Recipe")
        self.resize(300, 400)
        self.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(Recipe)
        self.centralwidget.setObjectName("centralwidget")

        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(0, 0, 150, 30))
        self.btn_back.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(156, 156, 156);")
        self.btn_back.setObjectName("btn_back")
        self.btn_back.clicked.connect(lambda: self.controller.showMainScreen())#showMainScreen

        self.btn_change = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change.setGeometry(QtCore.QRect(150, 0, 150, 30))
        self.btn_change.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(156, 156, 156);")
        self.btn_change.setObjectName("btn_change")
        self.btn_change.clicked.connect(lambda: self.controller.showChangeRecipe())#showChangeRecipe

        self.text_short_description = QtWidgets.QLabel(self.centralwidget)
        self.text_short_description.setGeometry(QtCore.QRect(0, 60, 300, 80))
        self.text_short_description.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_short_description.setObjectName("text_short_description")
        self.btn_like = QtWidgets.QPushButton(self.centralwidget)
        self.btn_like.setGeometry(QtCore.QRect(240, 30, 60, 30))
        self.btn_like.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"color: rgb(170, 0, 255);")
        self.btn_like.setObjectName("btn_like")
        self.text_likes = QtWidgets.QLabel(self.centralwidget)
        self.text_likes.setGeometry(QtCore.QRect(210, 30, 30, 30))
        self.text_likes.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_likes.setObjectName("text_likes")
        self.text_type_of_recipe = QtWidgets.QLabel(self.centralwidget)
        self.text_type_of_recipe.setGeometry(QtCore.QRect(0, 140, 300, 30))
        self.text_type_of_recipe.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_type_of_recipe.setObjectName("text_type_of_recipe")
        self.text_time = QtWidgets.QLabel(self.centralwidget)
        self.text_time.setGeometry(QtCore.QRect(240, 280, 60, 30))
        self.text_time.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_time.setObjectName("text_time")
        self.text_date = QtWidgets.QLabel(self.centralwidget)
        self.text_date.setGeometry(QtCore.QRect(0, 30, 90, 30))
        self.text_date.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_date.setObjectName("text_date")
        self.text_name_of_recipe = QtWidgets.QLabel(self.centralwidget)
        self.text_name_of_recipe.setGeometry(QtCore.QRect(90, 30, 150, 30))
        self.text_name_of_recipe.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_name_of_recipe.setObjectName("text_name_of_recipe")
        self.text_ingridients = QtWidgets.QLabel(self.centralwidget)
        self.text_ingridients.setGeometry(QtCore.QRect(0, 170, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_ingridients.setFont(font)
        self.text_ingridients.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_ingridients.setObjectName("text_ingridients")
        self.text_all_ingridients = QtWidgets.QLabel(self.centralwidget)
        self.text_all_ingridients.setGeometry(QtCore.QRect(0, 200, 300, 80))
        self.text_all_ingridients.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-color: rgb(178, 171, 255);")
        self.text_all_ingridients.setObjectName("text_all_ingridients")
        self.text_quantity_ingr = QtWidgets.QLabel(self.centralwidget)
        self.text_quantity_ingr.setGeometry(QtCore.QRect(250, 200, 50, 80))
        self.text_quantity_ingr.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"color: rgb(170, 0, 255);\n"
"border-color: rgb(178, 171, 255);")
        self.text_quantity_ingr.setObjectName("text_quantity_ingr")
        self.text_cook = QtWidgets.QLabel(self.centralwidget)
        self.text_cook.setGeometry(QtCore.QRect(0, 280, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_cook.setFont(font)
        self.text_cook.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_cook.setObjectName("text_cook")
        self.text_full_description = QtWidgets.QLabel(self.centralwidget)
        self.text_full_description.setGeometry(QtCore.QRect(0, 310, 300, 80))
        self.text_full_description.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"border-color: rgb(178, 171, 255);")
        self.text_full_description.setObjectName("text_full_description")
        self.btn_back.raise_()
        self.btn_change.raise_()
        self.text_short_description.raise_()
        self.btn_like.raise_()
        self.text_type_of_recipe.raise_()
        self.text_date.raise_()
        self.text_name_of_recipe.raise_()
        self.text_ingridients.raise_()
        self.text_all_ingridients.raise_()
        self.text_quantity_ingr.raise_()
        self.text_cook.raise_()
        self.text_time.raise_()
        self.text_likes.raise_()
        self.text_full_description.raise_()
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Recipe)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(Recipe)
        QtCore.QMetaObject.connectSlotsByName(Recipe)

    def retranslateUi(self, Recipe):
        _translate = QtCore.QCoreApplication.translate
        Recipe.setWindowTitle(_translate("Recipe", "Поваренная книга"))
        self.btn_back.setText(_translate("Recipe", "<-назад"))
        self.btn_change.setText(_translate("Recipe", "Редактировать"))
        self.text_short_description.setText(_translate("Recipe", "Традиционный шоколадный брауни с ванильным \n"
"ароматом, хрустящей корочкой и влажной \n"
"серединой"))
        self.btn_like.setText(_translate("Recipe", "лайк"))
        self.text_likes.setText(_translate("Recipe", "254"))
        self.text_type_of_recipe.setText(_translate("Recipe", "десерт, пирог, америкаская кухня"))
        self.text_time.setText(_translate("Recipe", "  40 мин."))
        self.text_date.setText(_translate("Recipe", "25 февр 2022"))
        self.text_name_of_recipe.setText(_translate("Recipe", "             Брауни"))
        self.text_ingridients.setText(_translate("Recipe", "Ингридиенты:"))
        self.text_all_ingridients.setText(_translate("Recipe", "Темный шоколад \n"
"Сливочное масло \n"
"Куриное яйцо \n"
"Сахар \n"
"Пшеничная мука"))
        self.text_quantity_ingr.setText(_translate("Recipe", "100гр \n"
"180гр \n"
"4шт \n"
"200гр \n"
"100гр"))
        self.text_cook.setText(_translate("Recipe", "Приготовление:"))
        self.text_full_description.setText(_translate("Recipe", "Масло и шоколад нужно растопить, для этого \n"
"шоколад ломаем кусочками и кладём \n"
"его вместе с маслом в ёмкость, в которой \n"
"будем их растапливать. Растапливаем шоколад \n"
" с маслом на водяной бане или в \n"
" микроволновой печи. "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Recipe = QtWidgets.QMainWindow()
    ui = Ui_Recipe()
    ui.setupUi(Recipe)
    Recipe.show()
    sys.exit(app.exec_())
