# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        Settings = QWidget()

        self.setObjectName("Settings")
        self.resize(300, 400)
        self.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(Settings)
        self.centralwidget.setObjectName("centralwidget")
        self.text_change_name = QtWidgets.QLabel(self.centralwidget)
        self.text_change_name.setGeometry(QtCore.QRect(20, 60, 260, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_change_name.setFont(font)
        self.text_change_name.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(213, 213, 213);")
        self.text_change_name.setObjectName("text_change_name")

        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(0, 0, 90, 30))
        self.btn_back.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(156, 156, 156);")
        self.btn_back.setObjectName("btn_back")
        self.btn_back.clicked.connect(lambda: self.controller.showProfile())#showProfile

        self.text_settings = QtWidgets.QLabel(self.centralwidget)
        self.text_settings.setGeometry(QtCore.QRect(90, 0, 210, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_settings.setFont(font)
        self.text_settings.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(213, 213, 213);")
        self.text_settings.setObjectName("text_settings")
        self.text_change_passw = QtWidgets.QLabel(self.centralwidget)
        self.text_change_passw.setGeometry(QtCore.QRect(20, 160, 260, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_change_passw.setFont(font)
        self.text_change_passw.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(213, 213, 213);")
        self.text_change_passw.setObjectName("text_change_passw")

        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(105, 290, 90, 30))
        self.btn_exit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(156, 156, 156);")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_exit.clicked.connect(lambda: self.controller.showProfile())#showProfile

        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(105, 330, 90, 30))
        self.btn_delete.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 12, 28); ")
        self.btn_delete.setObjectName("btn_delete")
        self.btn_delete.clicked.connect(lambda: self.controller.showFirst())#showFirst

        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Settings)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Поваренная книга"))
        self.text_change_name.setText(_translate("Settings", "Изменить имя"))
        self.btn_back.setText(_translate("Settings", "<-Назад"))
        self.text_settings.setText(_translate("Settings", "   Настройки"))
        self.text_change_passw.setText(_translate("Settings", "Изменить пароль"))
        self.btn_exit.setText(_translate("Settings", "Выход"))
        self.btn_delete.setText(_translate("Settings", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QMainWindow()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())
