# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Sort.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import (QApplication, QMainWindow, QPushButton,
                             QToolTip, QMessageBox, QLabel, QWidget)


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sort(QMainWindow, object):
    def __init__(self, c, m):
        super().__init__()
        self.model = m
        self.controller = c
        Sort = QWidget()

        self.setObjectName("Sort")
        self.resize(300, 400)
        self.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(Sort)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(0, 0, 80, 30))
        self.btn_cancel.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_cancel.clicked.connect(lambda: self.controller.showMainScreen())#showMainScreen

        self.btn_execute = QtWidgets.QPushButton(self.centralwidget)
        self.btn_execute.setGeometry(QtCore.QRect(220, 0, 80, 30))
        self.btn_execute.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);")
        self.btn_execute.setObjectName("btn_execute")
        self.btn_execute.clicked.connect(lambda: self.controller.showMainScreen())#showMainScreen

        self.text_type_of_recipe = QtWidgets.QLabel(self.centralwidget)
        self.text_type_of_recipe.setGeometry(QtCore.QRect(0, 180, 300, 61))
        self.text_type_of_recipe.setStyleSheet("background-color: rgb(166, 166, 166);\n"
"background-color: rgb(255, 255, 255);")
        self.text_type_of_recipe.setObjectName("text_type_of_recipe")
        self.text_name_of_recipe = QtWidgets.QLabel(self.centralwidget)
        self.text_name_of_recipe.setGeometry(QtCore.QRect(0, 30, 300, 30))
        self.text_name_of_recipe.setStyleSheet("color: rgb(177, 177, 177);\n"
"")
        self.text_name_of_recipe.setObjectName("text_name_of_recipe")
        self.text_want_ingridients = QtWidgets.QLabel(self.centralwidget)
        self.text_want_ingridients.setGeometry(QtCore.QRect(0, 240, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_want_ingridients.setFont(font)
        self.text_want_ingridients.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_want_ingridients.setObjectName("text_want_ingridients")
        self.text_no_ingridients2 = QtWidgets.QLabel(self.centralwidget)
        self.text_no_ingridients2.setGeometry(QtCore.QRect(0, 340, 300, 40))
        self.text_no_ingridients2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_no_ingridients2.setObjectName("text_no_ingridients2")
        self.text_sort_recipe = QtWidgets.QLabel(self.centralwidget)
        self.text_sort_recipe.setGeometry(QtCore.QRect(80, 0, 140, 30))
        self.text_sort_recipe.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_sort_recipe.setObjectName("text_sort_recipe")
        self.text_find_in_types = QtWidgets.QLabel(self.centralwidget)
        self.text_find_in_types.setGeometry(QtCore.QRect(0, 150, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_find_in_types.setFont(font)
        self.text_find_in_types.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_find_in_types.setObjectName("text_find_in_types")
        self.text_no_ingridients = QtWidgets.QLabel(self.centralwidget)
        self.text_no_ingridients.setGeometry(QtCore.QRect(0, 310, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_no_ingridients.setFont(font)
        self.text_no_ingridients.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_no_ingridients.setObjectName("text_no_ingridients")
        self.text_want_ingridients2 = QtWidgets.QLabel(self.centralwidget)
        self.text_want_ingridients2.setGeometry(QtCore.QRect(0, 270, 300, 40))
        self.text_want_ingridients2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_want_ingridients2.setObjectName("text_want_ingridients2")
        self.text_sort = QtWidgets.QLabel(self.centralwidget)
        self.text_sort.setGeometry(QtCore.QRect(0, 60, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_sort.setFont(font)
        self.text_sort.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"")
        self.text_sort.setObjectName("text_sort")
        self.btn_sort_by_rating = QtWidgets.QRadioButton(self.centralwidget)
        self.btn_sort_by_rating.setGeometry(QtCore.QRect(0, 90, 200, 20))
        self.btn_sort_by_rating.setObjectName("btn_sort_by_rating")
        self.btn_sort_by_date = QtWidgets.QRadioButton(self.centralwidget)
        self.btn_sort_by_date.setGeometry(QtCore.QRect(0, 110, 200, 20))
        self.btn_sort_by_date.setObjectName("btn_sort_by_date")
        self.btn_sort_by_time = QtWidgets.QRadioButton(self.centralwidget)
        self.btn_sort_by_time.setGeometry(QtCore.QRect(0, 130, 200, 20))
        self.btn_sort_by_time.setObjectName("btn_sort_by_time")
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Sort)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(Sort)
        QtCore.QMetaObject.connectSlotsByName(Sort)

    def retranslateUi(self, Sort):
        _translate = QtCore.QCoreApplication.translate
        Sort.setWindowTitle(_translate("Sort", "Поваренная книга"))
        self.btn_cancel.setText(_translate("Sort", "Х Отмена"))
        self.btn_execute.setText(_translate("Sort", "Выполнить"))
        self.text_type_of_recipe.setText(_translate("Sort", "десерт \n"
"пирог"))
        self.text_name_of_recipe.setText(_translate("Sort", "Название"))
        self.text_want_ingridients.setText(_translate("Sort", "Желаемые ингридиенты:"))
        self.text_no_ingridients2.setText(_translate("Sort", "Сахар"))
        self.text_sort_recipe.setText(_translate("Sort", "      Сортировка"))
        self.text_find_in_types.setText(_translate("Sort", "Искать в разделах:"))
        self.text_no_ingridients.setText(_translate("Sort", "Запрещенные ингридиенты:"))
        self.text_want_ingridients2.setText(_translate("Sort", "Шоколад"))
        self.text_sort.setText(_translate("Sort", "Сортировка:"))
        self.btn_sort_by_rating.setText(_translate("Sort", "по рейтингу"))
        self.btn_sort_by_date.setText(_translate("Sort", "по дате добавления"))
        self.btn_sort_by_time.setText(_translate("Sort", "по времени приготовления"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sort = QtWidgets.QMainWindow()
    ui = Ui_Sort()
    ui.setupUi(Sort)
    Sort.show()
    sys.exit(app.exec_())
